services:
  mysql:
    image: 'mysql:latest'
    container_name: mysql-container-appdb
    environment:
      - 'MYSQL_DATABASE=appdb'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=admin'
    ports:
      - '3307:3306'
