spring:
  application:
    name: auth-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: secret
    url: jdbc:mysql://localhost:3307/appdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
    show-sql: false


server:
  port: 8081

rsa:
  privateKey: classpath:certs/private.pem
  publicKey: classpath:certs/public.pem
